pipeline {
  agent any
  tools {
    nodejs '20.2.0'
    
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    //stage('Preparación del entorno') {
    //  steps {
    //    deleteDir() // Borra el workspace previo
    //    sh 'ls -la'
    //  }
    //}
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
    stage('Limpieza del entorno') {
      steps {
        deleteDir() // Borra el workspace al finalizar
      }
    }
  }
}
